mmrorate_model_list = ['cfa_r50_fpn_1x_dota_le135', 'cfa_r50_fpn_40e_dota_oc',
                       'rotated_retinanet_obb_csl_gaussian_r50_fpn_fp16_1x_dota_le90',
                       'g_reppoints_r50_fpn_1x_dota_le135', 'gliding_vertex_r50_fpn_1x_dota_le90',
                       'rotated_retinanet_hbb_gwd_r50_fpn_1x_dota_oc',
                       'rotated_retinanet_hbb_kfiou_r50_fpn_1x_dota_le90',
                       'rotated_retinanet_hbb_kfiou_r50_fpn_1x_dota_oc',
                       'rotated_retinanet_hbb_kfiou_r50_fpn_1x_dota_le135', 'r3det_kfiou_ln_r50_fpn_1x_dota_oc',
                       'rotated_retinanet_hbb_kld_r50_fpn_1x_dota_oc',
                       'rotated_retinanet_hbb_kld_stable_r50_fpn_1x_dota_oc',
                       'rotated_retinanet_obb_kld_stable_r50_fpn_1x_dota_le90', 'r3det_kld_r50_fpn_1x_dota_oc',
                       'r3det_kld_stable_r50_fpn_1x_dota_oc', 'r3det_tiny_kld_r50_fpn_1x_dota_oc',
                       'rotated_retinanet_hbb_kld_stable_r50_fpn_6x_hrsc_rr_oc',
                       'rotated_retinanet_obb_kld_stable_r50_fpn_6x_hrsc_rr_le90',
                       'rotated_retinanet_obb_kld_stable_r50_adamw_fpn_1x_dota_le90',
                       'oriented_rcnn_r50_fpn_fp16_1x_dota_le90', 'oriented_rcnn_r50_fpn_1x_dota_le90',
                       'r3det_r50_fpn_1x_dota_oc', 'r3det_tiny_r50_fpn_1x_dota_oc',
                       'redet_re50_refpn_fp16_1x_dota_le90', 'redet_re50_refpn_1x_dota_le90',
                       'redet_re50_refpn_1x_dota_ms_rr_le90', 'redet_re50_refpn_3x_hrsc_le90',
                       'roi_trans_r50_fpn_fp16_1x_dota_le90', 'roi_trans_r50_fpn_1x_dota_le90',
                       'roi_trans_swin_tiny_fpn_1x_dota_le90', 'roi_trans_r50_fpn_1x_dota_ms_le90',
                       'rotated_atss_hbb_r50_fpn_1x_dota_oc', 'rotated_atss_obb_r50_fpn_1x_dota_le90',
                       'rotated_atss_obb_r50_fpn_1x_dota_le135', 'rotated_faster_rcnn_r50_fpn_1x_dota_le90',
                       'rotated_fcos_sep_angle_r50_fpn_1x_dota_le90', 'rotated_fcos_r50_fpn_1x_dota_le90',
                       'rotated_fcos_csl_gaussian_r50_fpn_1x_dota_le90', 'rotated_fcos_kld_r50_fpn_1x_dota_le90',
                       'rotated_reppoints_r50_fpn_1x_dota_oc', 'rotated_retinanet_hbb_r50_fpn_1x_dota_oc',
                       'rotated_retinanet_obb_r50_fpn_1x_dota_le90', 'rotated_retinanet_obb_r50_fpn_fp16_1x_dota_le90',
                       'rotated_retinanet_obb_r50_fpn_1x_dota_le135',
                       'rotated_retinanet_obb_r50_fpn_1x_dota_ms_rr_le90',
                       'rotated_retinanet_hbb_r50_fpn_6x_hrsc_rr_oc', 'rotated_retinanet_obb_r50_fpn_6x_hrsc_rr_le90',
                       's2anet_r50_fpn_1x_dota_le135', 's2anet_r50_fpn_fp16_1x_dota_le135',
                       'sasm_reppoints_r50_fpn_1x_dota_oc']